name: Build and Release Plugin

on:
  push:
    branches:
      - '**'

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Extract plugin version
        id: get_version
        run: |
          version=$(grep '^pluginVersion=' gradle.properties | cut -d'=' -f2)
          echo "PLUGIN_VERSION=$version" >> $GITHUB_ENV

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Rename plugin artifact
        run: |
          mv build/distributions/*.zip YALI_${{ env.PLUGIN_VERSION }}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YALI_${{ env.PLUGIN_VERSION }}
          path: YALI_${{ env.PLUGIN_VERSION }}.zip

  release:
    if: github.ref == 'refs/heads/master'
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: YALI_${{ env.PLUGIN_VERSION }}

      - name: Create Release and Upload Artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PLUGIN_VERSION }}
          name: Release v${{ env.PLUGIN_VERSION }}
          files: YALI_${{ env.PLUGIN_VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 